version: "3.9"
services:
  bitcoind:
    image: ruimarinho/bitcoin-core:22.0
    command:
      - "-fallbackfee=0.00001"
      - "-regtest=1"
      - "-addresstype=bech32"
      - "-printtoconsole"
      - "-rpcallowip=0.0.0.0/0"
      - "-rpcbind=0.0.0.0"
      - "-rpcauth=test:6a7774db9eb48d9a8a631e145839c714$$f3a5564dff0103e4ffa96c212cf52ee8c0716d49f30f194c525f5a92ab972cf2"
      - "-zmqpubrawblock=tcp://0.0.0.0:29002"
      - "-zmqpubrawtx=tcp://0.0.0.0:29002"
      - "-zmqpubhashblock=tcp://0.0.0.0:29002"
      - "-zmqpubsequence=tcp://0.0.0.0:29002"
    ports:
      - "18443:18443"
      - "18444:18444"
      - "29002:29002"
    volumes:
      - ./.data/bitcoin:/home/bitcoin/.bitcoin

